listOfGraphicalSymbols=[]
listOfBindings=[]
listOfLayouts={}
ListOfInternalShellCommand={}
listOfPlatforms={}
listOfGenres={}
listOfLicences={}
listOfGames={}
listOfPossibleColumns=[]
listOflistSorting=[]
items=[]
THE_VISUAL_LIST_OF_GAMES=None
HIDED_DATA_COLUMN=9
titles = [" ", "Titre", "Licence", "Genre", "Date", "Dernière ouverture", "Temps cumulé", "Auteur", "Studio"]
items = []
STDSCR=None
